import {
  createTable,
  schemaMigrations,
} from "@nozbe/watermelondb/Schema/migrations";
import { name as UsersTableName } from "@/model/user";
import { name as DescongeladoSalmueraName } from "@/model/registros/Salmuera/RC_CC_15";
import { name as PeladoFrescoName } from "@/model/registros/ValorAgregado/RC_CC_103";
import { name as ProdTerminadoName } from "@/model/registros/ProdTerminado/RC_CC_108";
import { name as ProcesoEnteroName } from "@/model/registros/ProcesoEntero/RC_CC_07";

// Nota: Se debe especificar aqui lo mismo que en el esquema, pero no se puede usar el esquema
export default schemaMigrations({
  migrations: [
    {
      toVersion: 2, // Nueva versión del esquema
      steps: [
        createTable({
          name: UsersTableName, // Nombre de la tabla
          columns: [
            { name: "cedula", type: "string", isOptional: true },
            { name: "user_name", type: "string" },
            { name: "user_username", type: "string" },
            { name: "user_email", type: "string" },
            { name: "user_activo", type: "number" },
            { name: "user_password", type: "string" },
            { name: "rol_id", type: "number" },
            { name: "planta", type: "number", isOptional: true },
            { name: "area", type: "number", isOptional: true },
          ],
        }),
      ],
    },
    {
      toVersion: 3, // Nueva versión del esquema
      steps: [
        createTable({
          name: DescongeladoSalmueraName,
          columns: [
            { name: "tipo_analisis", type: "string" },
            { name: "co_importador", type: "string" },
            { name: "cabinplant", type: "string" },
            { name: "lote", type: "string" },
            { name: "proveedor", type: "string" },
            { name: "co_talla", type: "string" },
            { name: "pesoNetoFresco", type: "number" },
            { name: "peso_bruto", type: "number" },
            { name: "unidad_medida", type: "string" },
            { name: "pesoCongelado", type: "number" },
            { name: "pesoDescongelado", type: "number" },
            { name: "Cta_PesoNetoFresco", type: "number" },
            { name: "Cta_PesoCongelado", type: "number" },
            { name: "Cta_PesoDescongelado", type: "number" },
            { name: "observaciones", type: "string", isOptional: true },
            { name: "UsuCrea", type: "string", isOptional: true },
            { name: "FechaCrea", type: "string", isOptional: true },
            { name: "UsuModi", type: "string", isOptional: true },
            { name: "FechaModi", type: "string", isOptional: true },
            { name: "correccionBln", type: "number" },
            { name: "estado", type: "number" },
            { name: "state", type: "number" },
            { name: "planta_id", type: "number", isOptional: true },
          ],
        }),
        createTable({
          name: PeladoFrescoName,
          columns: [
            { name: "unidad_peso", type: "string" },
            { name: "tipo_corte", type: "string" },
            { name: "lote", type: "string" },
            { name: "co_importador", type: "number" },
            { name: "name_importador", type: "string" },
            { name: "co_talla", type: "number" },
            { name: "name_talla", type: "string" },
            { name: "area", type: "string" },
            { name: "peso_muestra", type: "number" },
            { name: "cuenta_libra", type: "number" },
            { name: "uniformidad_p", type: "number" },
            { name: "uniformidad_g", type: "number" },
            { name: "uniformidad_total", type: "number" },
            { name: "corte_irregular", type: "number" },
            { name: "corte_largo", type: "number" },
            { name: "corte_profundo", type: "number" },
            { name: "falta_corte", type: "number" },
            { name: "pud", type: "number" },
            { name: "cascaras", type: "number" },
            { name: "patas", type: "number" },
            { name: "p_melanosis", type: "number" },
            { name: "melanosis", type: "number" },
            { name: "semirosado", type: "number" },
            { name: "rosado", type: "number" },
            { name: "mudado", type: "number" },
            { name: "flacido", type: "number" },
            { name: "picado", type: "number" },
            { name: "deshidratados", type: "number" },
            { name: "pedazos", type: "number" },
            { name: "quebrado", type: "number" },
            { name: "quebrado_3er", type: "number" },
            { name: "sin_telson", type: "number" },
            { name: "corbata", type: "number" },
            { name: "deforme", type: "number" },
            { name: "mal_descabezado", type: "number" },
            { name: "juvenil", type: "number" },
            { name: "intestinos", type: "number" },
            { name: "residuo_venas", type: "number" },
            { name: "cascara_floja", type: "number" },
            { name: "cascara_floja_6to", type: "number" },
            { name: "total_defectos", type: "number" },
            { name: "calidad", type: "string" },
            { name: "olor", type: "string" },
            { name: "sabor", type: "string" },
            { name: "temperatura", type: "number" },
            { name: "sulfito", type: "string" },
            { name: "observacion", type: "string", isOptional: true },
            { name: "UsuCrea", type: "string", isOptional: true },
            { name: "FechaCrea", type: "string", isOptional: true },
            { name: "UsuModi", type: "string", isOptional: true },
            { name: "FechaModi", type: "string", isOptional: true },
            { name: "correccion", type: "number" },
            { name: "foto", type: "number" },
            { name: "state", type: "number" },
            { name: "planta_id", type: "number", isOptional: true },
          ],
        }),
        createTable({
          name: ProdTerminadoName,
          columns: [
            { name: "fecha_etiqueta", type: "string" },
            { name: "tipo_control", type: "string" },
            { name: "area", type: "string" },
            { name: "tipo_producto", type: "string" },
            { name: "presentacion", type: "string" },
            { name: "unidad_medida", type: "string" },
            { name: "tipo_muestreo", type: "string" },
            { name: "lote", type: "string" },
            { name: "cliente", type: "number" },
            { name: "temperatura", type: "number" },
            { name: "talla_real", type: "number" },
            { name: "talla_marcada", type: "number" },
            { name: "peso_bruto", type: "number" },
            { name: "peso_sin_funda", type: "number" },
            { name: "peso_neto", type: "number" },
            { name: "glaseo", type: "number" },
            { name: "cta_congelada", type: "number" },
            { name: "cta_final", type: "number" },
            { name: "cuenta_total", type: "number" },
            { name: "peso_muestra", type: "number", isOptional: true },
            { name: "olor", type: "string" },
            { name: "sabor", type: "string" },
            { name: "uniformidad_g", type: "number" },
            { name: "uniformidad_p", type: "number" },
            { name: "uniformidad_t", type: "number" },
            { name: "state", type: "number" },
            { name: "observacion", type: "string", isOptional: true },
            { name: "UsuCrea", type: "string", isOptional: true },
            { name: "FechaCrea", type: "string", isOptional: true },
            { name: "UsuModi", type: "string", isOptional: true },
            { name: "FechaModi", type: "string", isOptional: true },
            { name: "planta_id", type: "number", isOptional: true },
          ],
        }),
        createTable({
          name: ProcesoEnteroName,
          columns: [
            { name: "Fecha", type: "string" },
            { name: "co_maquina", type: "number" },
            { name: "Marca", type: "number" },
            { name: "Importador", type: "number" },
            { name: "Proveedor", type: "string", isOptional: true },
            { name: "unidad", type: "string" },
            { name: "Lote", type: "string" },
            { name: "co_talla", type: "number" },
            { name: "Peso_Bruto", type: "number" },
            { name: "Peso_Neto", type: "number" },
            { name: "peso_muestra", type: "number" },
            { name: "Cuenta_Total", type: "number" },
            { name: "CuentaXLibra", type: "number" },
            { name: "UniformidadG", type: "number" },
            { name: "UniformidadP", type: "number" },
            { name: "uniformidadUT", type: "number" },
            { name: "hora_analisis", type: "string" },
            { name: "Cabeza_Anaranjada", type: "number" },
            { name: "Cabeza_Floja", type: "number" },
            { name: "Cabeza_Descolgada", type: "number" },
            { name: "Hepatopanc", type: "number" },
            { name: "Flacidos", type: "number" },
            { name: "Mudados", type: "number" },
            { name: "Cabeza_Roja", type: "number" },
            { name: "Melanosis", type: "number" },
            { name: "deshidratados_leve", type: "number" },
            { name: "deshidratados_fuerte", type: "number" },
            { name: "picado_leve", type: "number" },
            { name: "picado_fuerte", type: "number" },
            { name: "branquias_sucias", type: "number" },
            { name: "branquias_verdes", type: "number" },
            { name: "principio_melanosis", type: "number" },
            { name: "Juveniles", type: "number" },
            { name: "Deformes", type: "number" },
            { name: "Quebrados", type: "number" },
            { name: "Materiales_extranos", type: "number" },
            { name: "Total_Defectos", type: "number" },
            { name: "Necrosis", type: "string" },
            { name: "Temperatura", type: "number" },
            { name: "Declara_Sulfitos", type: "string" },
            { name: "Observaciones", type: "string", isOptional: true },
            { name: "UsuCrea", type: "string", isOptional: true },
            { name: "FechaCrea", type: "string", isOptional: true },
            { name: "UsuModi", type: "string", isOptional: true },
            { name: "FechaModi", type: "string", isOptional: true },
            { name: "correccion", type: "number" },
            { name: "foto", type: "number" },
            { name: "planta_id", type: "number", isOptional: true },
            { name: "state", type: "number" },
          ],
        }),
      ],
    },
  ],
});
